[options]
admin_passwd = $pbkdf2-sha512$600000$GwMAoPQewzgHgDDmnDMmpA$wqYtT2aIi7ruV7/9dwDrsc3uouXQcnCdDvd9Kz8aVe.WYxGLVGNQcWX3Jz701yrreOpzZSbTQDmOtKTz1wh9ow
logfile = D:/Manuel/Empresas/ERP/OpenSource/odoo/odoo.log
log_level = debug
log_handler = :DEBUG
; --- GEOIP ---
; Apuntamos al archivo específico dentro de la carpeta.
; IMPORTANTE: Asegúrate de que el archivo se llame 'GeoLite2-City.mmdb'
geoip_city_db = D:/Manuel/Empresas/ERP/OpenSource/odoo/GeoIP/GeoLite2-City.mmdb

