{
    'name': 'Supply Chain Approvals Pro',
    'version': '18.0.3.0.0',
    'category': 'Inventory/Purchase',
    'summary': 'Flujo de aprobaciones mancomunadas configurables por usuario',
    'author': 'Mejores Horizontes - Manuel Mesones',
    'depends': ['base', 'purchase','purchase_requisition', 'stock', 'account'],
    'data': [
        'security/security.xml',
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'wizard/approval_wizard_view.xml',
        'views/purchase_requisition_views.xml',
        'views/purchase_order_views.xml',
        'views/stock_picking_views.xml',
        'views/account_move_views.xml',
        'views/account_payment_views.xml',
        'views/approval_route_views.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}