{
    'name': 'Education Core Management',
    'version': '18.0.1.0.0',
    'summary': 'Núcleo de gestión académica para Colegios, Institutos y Universidades',
    'category': 'Education',
    'author': 'Mejores Horizontes - Manuel Mesones',
    'license': 'AGPL-3',
    'depends': [
        'base',
        'hr',
        'calendar',
    ],
    'data': [
        'security/education_security.xml',
        'security/ir.model.access.csv',
        'views/res_partner_views.xml',
        'views/hr_employee_views.xml',
        'views/education_academic_period_views.xml',
        'views/education_classroom_views.xml',
        'views/education_course_views.xml',
        'views/education_section_views.xml',
        'views/education_enrollment_views.xml',
        'views/menu_views.xml',
        'report/education_section_report.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}